apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ .Values.env.secret.name }}
data:
  config-secret.js: |- # Using the indent because the the decoded text is multi-line string
  {{ .Values.env.secret.secretCode | indent 8 }}
